name: Deploy

on:
    push:
        branches:
          - master
          - production

jobs:
  deploy:
    name: Deploy to PyPI
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=target_branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Install bumpversion
        run: pip install bump2version
      - name: Install pypa/build
        run: >-
          python -m
          pip install
          build
          --user
      - name: Set-up git
        run: |
          git config --global user.email "zandersstijn@gmail.com"
          git config --global user.name "Stijn Zanders"
      - name: Bump version master
        if: steps.extract_branch.outputs.target_branch == 'master'
        run: |
          bumpversion patch
          git push
      - name: Tag production
        if: steps.extract_branch.outputs.target_branch == 'production'
        run: |
          bumpversion --tag release --no-commit
          git push --tags
      - name: Build a binary wheel and a source tarball
        run: >-
          python -m
          build
          --sdist
          --wheel
          --outdir dist/
      - name: Publish distribution ðŸ“¦ to Test PyPI for master
        if: steps.extract_branch.outputs.target_branch == 'master'
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_TEST_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
      - name: Publish distribution ðŸ“¦ to PyPI for production
        if: steps.extract_branch.outputs.target_branch == 'production'
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_TOKEN }}